### ISSUE TITLE
content? Salt/Salt+ ?

### ISSUE THREAD

**Issue by x37v** [BelaPlatform/modular#1]
Is this where we'll see schematics and PCB layout info for the Salt/Salt+ projects? If so, when?

**Comment by giuliomoro** [comment]
maybe ... still thinking about where the best place for that would be. In a couple of weeks.

**Comment by x37v** [comment]
but you are planning to release the source for that?

**Comment by giuliomoro** [comment]
they will be, at least the schematics and BOM. Possibly the PCB as well.
